{% set version = "0.5.1" %}
{% set sha256 = "385fb216e7d1241f70c14c2bea3f042ec235caa65d708294f1ece50d3efa5de3" %}
{% set build = 2 %}

package:
  name: python-snappy
  version: "{{ version }}"

source:
  fn: python-snappy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-snappy/python-snappy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: CPATH="$PREFIX/include:$CPATH" LIBDIR="$PREFIX/lib" python setup.py install  # [unix]
  script: python setup.py install  # [win]

requirements:
  build:
    - python
    - cmake
    - snappy 1.1.6|1.1.7
    - toolchain
  run:
    - python
    - snappy 1.1.6|1.1.7

test:
  imports:
     - snappy

about:
  home: http://github.com/andrix/python-snappy
  license: BSD 3-clause
  summary: 'Python library for the snappy compression library from Google'


extra:
  recipe-maintainers:
    - mariusvniekerk
    - martindurant
