{% set name = "python-snappy" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: python-snappy-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/python-snappy/python_snappy-{{ version }}.tar.gz
  sha256: 40216c1badfb2d38ac781ecb162a1d0ec40f8ee9747e610bcfefdfa79486cee3
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - snappy
    - cramjam >=2.6.0
  run:
    - python
    - cramjam

test:
  requires:
    - python
    - pip
  imports:
    - snappy
  commands:
    - pip check

about:
  home: https://github.com/andrix/python-snappy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for the snappy compression library from Google
  description: |
    Python library for the snappy compression library from Google
  dev_url: https://github.com/andrix/python-snappy
  doc_url: https://github.com/andrix/python-snappy

extra:
  recipe-maintainers:
    - mariusvniekerk
    - martindurant
    - djsutherland
