travis:
  secure:
    BINSTAR_TOKEN: C6mpcA1BgKlO7mHD/6Hf9HFoXt3q9EEKRqtOo4xDHHEoqIigc4J105WyRxLGzD1td70XbkAe6Uz7xNrkvrITel2fHyy6xmNpzpTzaj+NBusXhd7LZ1V60rf75b6TilEUrwBXBxiCxdpaNLOtEdrGDd8oMeV8YwH9ttNY9wMVY74Qq9dCl0Tg2+tVYsSsZOISZipfMG+49nGf5CKqccLcCMpn8d9lZUuAQ2L1zwOfj/ij9VR0wGlW9BJG5XGdvqqfWFtljJisW25Ua9A8KGbxbWSg1L1DgEUISjHN6t/bILLRrN0DEWCVfY1BDfCgUc1T/GP53hkeJK95k/d2/jK/DV6sucJi0Nx35tr3ieeHnMDspCvtHDWpZTK4+1vuB2/cb8Likgtx8I6IsSanu4EbWQvRS+k264lnzJPH/oyVEMJ4xmg6fSOVyWK3xGVttfbRkMQO4hWN2QQMQUHJL1GgiZwMoXhwRTPYTsZuhtuzRqXV/Z8SEQbCc5dFHn5tE75FSGhdQ0bnuVRuFIBuTCKK4vbTllz638azcrBpdTglHxWHGssIGMg2O2VRfqZOuTrUKaaNUBbmi/9oezz1HwYQ5KCP8UBgW3tbytzv+S7OjzSw0sXF15tZnIo1i6XZHcJSMhBOhCWlgHaJkCRGT5tftPwbdkT2KdCVpjz/wnL5XPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
